/**
 * Utility to get Monaco worker URLs with hashed filenames
 * Workers are generated by the bundler with content hashes
 * 
 * The bundler creates worker files with hashed names (e.g., json.worker.b816b254.js).
 * We only need JSON support, so we only configure the JSON worker.
 */

// Cache for worker URLs to avoid repeated lookups
const workerUrlCache: Record<string, string> = {}

/**
 * Get Monaco worker URL for a given language label
 * Only supports JSON - other languages will use the editor worker as fallback
 */
export async function getMonacoWorkerUrl(label: string): Promise<string> {
  // Check cache first
  if (workerUrlCache[label]) {
    return workerUrlCache[label]
  }

  const basePath = chrome.runtime.getURL("")
  
  // Only JSON is supported - all other languages fall back to editor worker
  const workerBase = label.toLowerCase() === "json" ? "json.worker" : "editor.worker"
  
  try {
    const workerUrl = `${basePath}${workerBase}.js`
    workerUrlCache[label] = workerUrl
    return workerUrl
  } catch (error) {
    // Fallback to base filename
    const workerUrl = `${basePath}${workerBase}.js`
    workerUrlCache[label] = workerUrl
    return workerUrl
  }
}

/**
 * Initialize Monaco environment with worker configuration
 * Only configures JSON worker - other languages will use editor worker as fallback
 * This should be called before creating any Monaco editor instances
 */
export function initMonacoEnvironment() {
  if (typeof window === "undefined") return

  ;(window as any).MonacoEnvironment = {
    getWorkerUrl: async function (_moduleId: string, label: string) {
      const basePath = chrome.runtime.getURL("")
      // Only JSON is supported - all other languages fall back to editor worker
      const workerFile = label.toLowerCase() === "json" ? "json.worker.js" : "editor.worker.js"
      return `${basePath}${workerFile}`
    },
  }
}

